import type { TestCenterStoreType } from 'schemas';

export const state = {
  step: 1,
  readyToSubmit: false,
  testCenter: {
    testCenterName: 'James Finley',
    testCenterType: 'Quia rerum omnis vol',
    alternateCoordinator: { firstName: '', lastName: '', email: '', phone: '' },
    primaryCoordinator: { firstName: '', lastName: '', email: '', phone: '' },
    shippingPoc: { firstName: '', lastName: '', email: '', phone: '' },
    techCoordinator: { firstName: '', lastName: '', email: '', phone: '' },
    reportingAddress: {
      country: 'United States of America',
      countryIsoCd: 'US',
      address1: 'Address 1',
      address2: 'Address 2',
      address3: 'Address 3',
      city: 'City',
      intlPostalCd: '',
      regionName: '',
      state: 'Virginia',
      stateCd: 'VA',
      zip4: '4444',
      zip5: '55555',
    },
    shippingAddress: {
      country: 'United States of America',
      countryIsoCd: 'US',
      address1: 'Address 1',
      address2: 'Address 2',
      address3: 'Address 3',
      city: 'City',
      intlPostalCd: '',
      regionName: '',
      state: 'Virginia',
      stateCd: 'VA',
      zip4: '4444',
      zip5: '55555',
    },
  },
};

export const state2: TestCenterStoreType = {
  step: 1,
  readyToSubmit: false,
  testCenter: {
    testCenterName: 'Zia Kirk',
    testCenterType: 'Veritatis ad sed lab',
    alternateCoordinator: {
      firstName: 'Tatum',
      lastName: 'Wells',
      email: 'tesonob@mailinator.com',
      phone: '+1 (105) 147-8384',
    },
    primaryCoordinator: {
      firstName: 'Azalia',
      lastName: 'Robles',
      email: 'xilawov@mailinator.com',
      phone: '+1 (747) 635-7543',
    },
    shippingPoc: {
      firstName: 'Keefe',
      lastName: 'Wilkins',
      email: 'fyzyqyqi@mailinator.com',
      phone: '+1 (156) 275-8443',
    },
    techCoordinator: {
      firstName: 'Maxine',
      lastName: 'Sargent',
      email: 'xubumuwoje@mailinator.com',
      phone: '+1 (288) 313-1218',
    },
    reportingAddress: {
      country: 'United States of America',
      countryIsoCd: 'US',
      address1: '887 First Lane',
      address2: 'Est consequatur Sit',
      address3: 'Praesentium consequa',
      city: 'Consequatur Cum rep',
      intlPostalCd: '',
      regionName: '',
      state: 'Virginia',
      stateCd: 'VA',
      zip4: '4444',
      zip5: '55555',
    },
    shippingAddress: {
      country: 'Aruba',
      countryIsoCd: 'AW',
      address1: '19 Clarendon Drive',
      address2: 'Eius eaque veniam d',
      address3: 'Excepturi deleniti q',
      city: 'Quis consequatur ame',
      intlPostalCd: '555555',
      regionName: 'Teagan Campbell',
      state: '',
      stateCd: '',
      zip4: '',
      zip5: '',
    },
  },
};
